name: Testing Job

on:
  workflow_dispatch:

jobs:
  check_variable:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: Set variables
       run: |
        BUILD_TRIGGER_DESC = "${{github.event_name}} by ${{github.actor}}"
        BUILD_TRIGGER_BY = "${{github.actor}}"
        echo BUILD_TRIGGER_DESC