name: Testing Job

on: [push]

jobs:
  check_variable:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: Set variables
       run: |
        echo "BUILD_TRIGGER_DESC=${{ github.event_name }} by ${{ github.actor }}" >> $GITHUB_ENV
        echo "BUILD_TRIGGER_BY=${{ github.actor }}" >> $GITHUB_ENV

     - name: Check variables
       run: |
        echo "Build Trigger Description: $BUILD_TRIGGER_DESC"
        echo "Build Triggered By: $BUILD_TRIGGER_BY"
