name: Testing Job

on:
  schedule:
    # Runs every 30 minutes between 4:00 AM and 5:00 AM UTC (which is 8:00 PM to 9:00 PM PST)
    - cron: '0,30 14 * * 1-5'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  trigger_replication: 
    # runs on the docker in docker runner set provided.
    runs-on: ubuntu-latest

    steps:
    # checks out the website-replication-automation repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Check if it's 8:30 PM PST
    - name: Check if it's 8:30 PM PST/PDT
      id: check_time
      run: |
        current_hour=$(date +"%H")
        current_minute=$(date +"%M")
        timezone=$(date +"%Z")
        echo "Current Hour -> $current_hour"
        echo "Current Minutes -> $current_minute"
        echo "Timezone -> timezone$"
        if [[ "$timezone" == "PST" && "$current_hour" == "04" && "$current_minute" == "30" ]] || 
           [[ "$timezone" == "PDT" && "$current_hour" == "03" && "$current_minute" == "30" ]]; then
          echo "It's 8:30 PM in PST/PDT. Proceeding with the workflow."
        else
          echo "Not the correct time. Exiting."
          exit 0
        fi

    - name: Set variables
      #  env: 
      #   API_KEY: ${{ env.API_KEY }}
      #   PASSWORD: ${{ secrets.PASSWORD }}
      if: steps.check_time.outcome == 'success'
      run: |
        echo "BUILD_TRIGGER_DESC=${{ github.event_name }} by ${{ github.actor }}" >> $GITHUB_ENV
        echo "BUILD_TRIGGER_BY=${{ github.actor }}" >> $GITHUB_ENV
        # echo $API_KEY
        # echo $PASSWORD

    - name: Check variables
      if: steps.check_time.outcome == 'success'
      run: |
        echo "Build Trigger Description: $BUILD_TRIGGER_DESC"
        echo "Build Triggered By: $BUILD_TRIGGER_BY"